//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccentureProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libros()
        {
            this.LibrosXAutores = new HashSet<LibrosXAutores>();
        }
    
        public int IdLibro { get; set; }
        public string Titulo { get; set; }
        public string ISBN { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public string Sinopsis { get; set; }
        public int Id_Editorial { get; set; }
        public int Id_Genero { get; set; }
        public int Id_Autor { get; set; }
    
        public virtual Autores Autores { get; set; }
        public virtual Editoriales Editoriales { get; set; }
        public virtual Generos Generos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LibrosXAutores> LibrosXAutores { get; set; }
    }
}
